### PR TITLE
updated to latest versions, fixed release mode launch

### PR DESCRIPTION
**Pull request by billtlee**
Updated all packages to latest versions, except ethers (update to latest 3.x version).  Made some minor changes to support new version of react-navigation in route.js

### CODE REVIEW

**Comment by fmsouza** [comment]
Sorry for taking so long to review. I just downloaded your branch to run locally, and it does not build.

**Comment by billtlee** [comment]
Hmm, I'm able to run it using yarn ios and build it in Xcode in release mode...  What errors are you getting?  Maybe try react-native link first?

Screen Shot 2019-06-05 at 3 00 18 PM
Screen Shot 2019-06-05 at 3 04 33 PM
Screen Shot 2019-06-05 at 3 09 38 PM

**Comment by fmsouza** [comment]
Yeah, doing this way works. I tried with Android. But there's no problem, at least it's a good point to start from. There's just a conflict with `master` in your branch. Could you please resolve it so I can merge?

**Comment by billtlee** [comment]
How do I resolve?  The button is greyed out...

Screen Shot 2019-06-06 at 8 11 19 AM

**Comment by fmsouza** [comment]
In your fork, pull the changes from my master. You will pull the
conflicting changes. Then you resolve locally, commit the changes and push
again.

Em qua, 5 de jun de 2019 21:12, billtlee <notifications@github.com>
escreveu:

**Comment by billtlee** [comment]
I did a git pull origin master, git commit and push from my branch but didn't see any conflict.  perhaps package-lock.json is in gitignore?

**Comment by fmsouza** [comment]
Looks like you didn't pulled from the source's branch. Try that:
```
$ git pull https://github.com/fmsouza/ethereum-wallet.git master
```

**Comment by billtlee** [comment]
ok, done. try it now...

**Pull request merged**
